### ISSUE TITLE
Failed to set up development environment

### ISSUE THREAD

**Issue by smulube** [DECODEproject/decodev2#1]
Hi I encountered a problem in setting up my local development environment which @jordibuj was helping me with on Telegram, but documenting it here to capture my problem in a better place.

The problem I have is that when I clone the repo and try to set up a development environment (which I'm defining as being able to run the test suite successfully) - the test suite fails with a cryptic error when trying to run `applications.spec.js`.
## System configuration

Variable | Value
----------- | -------------------
OS | Ubuntu 18.04.3 LTS
Node version | v8.16.1
Yarn version | 1.17.3
Android studio installed | false
Xcode installed | false

## Steps to reproduce

1. Clone the repo locally and change into the project directory
2. Install node dependencies by running `yarn install`
3. Copy the `.env.sample` file in the project root to a file named `.env`
4. Insert the following text into the `.env` file:
    ```
    STORAGE_KEY=48656c6c6f20576f726c6421
    SENTRY_DSN=http://sentry.io
    ```
5. Run the tests by executing `yarn test`

When I follow the above steps I see the following error output:

```
yarn run v1.17.3
$ eslint . && jest
PASS __tests__/migrations.spec.js
FAIL __tests__/attributes.spec.js
  ● Attribute tests › Add attribute

    Array contains invalid value: 15,NaN

      47 |   const buffer = [];
      48 |   const iv = uuid(null, buffer);
    > 49 |   const aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
         |                  ^
      50 |   const encryptedBytes = aesCbc.encrypt(paddedBytes);
      51 |   const encryptedHex = aesjs.utils.hex.fromBytes([...iv, ...encryptedBytes]);
      52 |   return encryptedHex;

      at coerceArray (node_modules/aes-js/index.js:40:23)
      at new coerceArray (node_modules/aes-js/index.js:195:20)
      at new ModeOfOperationCBC (node_modules/aes-js/index.js:444:21)
      at encrypt (src/lib/utils.js:49:18)
      at _default (src/redux/modules/attributes.js:158:15)
      at Object.<anonymous> (__tests__/attributes.spec.js:45:21)

  ● Attribute tests › Encrypt

    Array contains invalid value: 15,NaN

      47 |   const buffer = [];
      48 |   const iv = uuid(null, buffer);
    > 49 |   const aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
         |                  ^
      50 |   const encryptedBytes = aesCbc.encrypt(paddedBytes);
      51 |   const encryptedHex = aesjs.utils.hex.fromBytes([...iv, ...encryptedBytes]);
      52 |   return encryptedHex;

      at coerceArray (node_modules/aes-js/index.js:40:23)
      at new coerceArray (node_modules/aes-js/index.js:195:20)
      at new ModeOfOperationCBC (node_modules/aes-js/index.js:444:21)
      at encrypt (src/lib/utils.js:49:18)
      at Object.<anonymous> (__tests__/attributes.spec.js:51:20)

  ● Attribute tests › Change attribute

    Array contains invalid value: 15,NaN

      47 |   const buffer = [];
      48 |   const iv = uuid(null, buffer);
    > 49 |   const aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
         |                  ^
      50 |   const encryptedBytes = aesCbc.encrypt(paddedBytes);
      51 |   const encryptedHex = aesjs.utils.hex.fromBytes([...iv, ...encryptedBytes]);
      52 |   return encryptedHex;

      at coerceArray (node_modules/aes-js/index.js:40:23)
      at new coerceArray (node_modules/aes-js/index.js:195:20)
      at new ModeOfOperationCBC (node_modules/aes-js/index.js:444:21)
      at encrypt (src/lib/utils.js:49:18)
      at Object.<anonymous> (__tests__/attributes.spec.js:62:19)

  ● Attribute tests › Change attribute and getAllAttributes

    Array contains invalid value: 15,NaN

      47 |   const buffer = [];
      48 |   const iv = uuid(null, buffer);
    > 49 |   const aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
         |                  ^
      50 |   const encryptedBytes = aesCbc.encrypt(paddedBytes);
      51 |   const encryptedHex = aesjs.utils.hex.fromBytes([...iv, ...encryptedBytes]);
      52 |   return encryptedHex;

      at coerceArray (node_modules/aes-js/index.js:40:23)
      at new coerceArray (node_modules/aes-js/index.js:195:20)
      at new ModeOfOperationCBC (node_modules/aes-js/index.js:444:21)
      at encrypt (src/lib/utils.js:49:18)
      at Object.<anonymous> (__tests__/attributes.spec.js:72:17)

  ● Attribute tests › Add another attribute

    Array contains invalid value: 15,NaN

      47 |   const buffer = [];
      48 |   const iv = uuid(null, buffer);
    > 49 |   const aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
         |                  ^
      50 |   const encryptedBytes = aesCbc.encrypt(paddedBytes);
      51 |   const encryptedHex = aesjs.utils.hex.fromBytes([...iv, ...encryptedBytes]);
      52 |   return encryptedHex;

      at coerceArray (node_modules/aes-js/index.js:40:23)
      at new coerceArray (node_modules/aes-js/index.js:195:20)
      at new ModeOfOperationCBC (node_modules/aes-js/index.js:444:21)
      at encrypt (src/lib/utils.js:49:18)
      at Object.<anonymous> (__tests__/attributes.spec.js:81:17)

  ● Attribute tests › Attribute selector

    Array contains invalid value: 15,NaN

      47 |   const buffer = [];
      48 |   const iv = uuid(null, buffer);
    > 49 |   const aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
         |                  ^
      50 |   const encryptedBytes = aesCbc.encrypt(paddedBytes);
      51 |   const encryptedHex = aesjs.utils.hex.fromBytes([...iv, ...encryptedBytes]);
      52 |   return encryptedHex;

      at coerceArray (node_modules/aes-js/index.js:40:23)
      at new coerceArray (node_modules/aes-js/index.js:195:20)
      at new ModeOfOperationCBC (node_modules/aes-js/index.js:444:21)
      at encrypt (src/lib/utils.js:49:18)
      at Object.<anonymous> (__tests__/attributes.spec.js:97:17)

  ● Attribute tests › All attributes selector

    Array contains invalid value: 15,NaN

      47 |   const buffer = [];
      48 |   const iv = uuid(null, buffer);
    > 49 |   const aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
         |                  ^
      50 |   const encryptedBytes = aesCbc.encrypt(paddedBytes);
      51 |   const encryptedHex = aesjs.utils.hex.fromBytes([...iv, ...encryptedBytes]);
      52 |   return encryptedHex;

      at coerceArray (node_modules/aes-js/index.js:40:23)
      at new coerceArray (node_modules/aes-js/index.js:195:20)
      at new ModeOfOperationCBC (node_modules/aes-js/index.js:444:21)
      at encrypt (src/lib/utils.js:49:18)
      at Object.<anonymous> (__tests__/attributes.spec.js:105:17)

  ● Attribute tests › All attribute names

    Array contains invalid value: 15,NaN

      47 |   const buffer = [];
      48 |   const iv = uuid(null, buffer);
    > 49 |   const aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
         |                  ^
      50 |   const encryptedBytes = aesCbc.encrypt(paddedBytes);
      51 |   const encryptedHex = aesjs.utils.hex.fromBytes([...iv, ...encryptedBytes]);
      52 |   return encryptedHex;

      at coerceArray (node_modules/aes-js/index.js:40:23)
      at new coerceArray (node_modules/aes-js/index.js:195:20)
      at new ModeOfOperationCBC (node_modules/aes-js/index.js:444:21)
      at encrypt (src/lib/utils.js:49:18)
      at Object.<anonymous> (__tests__/attributes.spec.js:128:17)

  ● Attribute tests › Filter atlas attributes

    Array contains invalid value: 15,NaN

      47 |   const buffer = [];
      48 |   const iv = uuid(null, buffer);
    > 49 |   const aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
         |                  ^
      50 |   const encryptedBytes = aesCbc.encrypt(paddedBytes);
      51 |   const encryptedHex = aesjs.utils.hex.fromBytes([...iv, ...encryptedBytes]);
      52 |   return encryptedHex;

      at coerceArray (node_modules/aes-js/index.js:40:23)
      at new coerceArray (node_modules/aes-js/index.js:195:20)
      at new ModeOfOperationCBC (node_modules/aes-js/index.js:444:21)
      at encrypt (src/lib/utils.js:49:18)
      at Object.<anonymous> (__tests__/attributes.spec.js:137:17)

  ● Attribute tests › Filter atlas attributes - all

    Array contains invalid value: 15,NaN

      47 |   const buffer = [];
      48 |   const iv = uuid(null, buffer);
    > 49 |   const aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
         |                  ^
      50 |   const encryptedBytes = aesCbc.encrypt(paddedBytes);
      51 |   const encryptedHex = aesjs.utils.hex.fromBytes([...iv, ...encryptedBytes]);
      52 |   return encryptedHex;

      at coerceArray (node_modules/aes-js/index.js:40:23)
      at new coerceArray (node_modules/aes-js/index.js:195:20)
      at new ModeOfOperationCBC (node_modules/aes-js/index.js:444:21)
      at encrypt (src/lib/utils.js:49:18)
      at Object.<anonymous> (__tests__/attributes.spec.js:146:17)

  ● Attribute tests › Delete attribute

    Array contains invalid value: 15,NaN

      47 |   const buffer = [];
      48 |   const iv = uuid(null, buffer);
    > 49 |   const aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
         |                  ^
      50 |   const encryptedBytes = aesCbc.encrypt(paddedBytes);
      51 |   const encryptedHex = aesjs.utils.hex.fromBytes([...iv, ...encryptedBytes]);
      52 |   return encryptedHex;

      at coerceArray (node_modules/aes-js/index.js:40:23)
      at new coerceArray (node_modules/aes-js/index.js:195:20)
      at new ModeOfOperationCBC (node_modules/aes-js/index.js:444:21)
      at encrypt (src/lib/utils.js:49:18)
      at Object.<anonymous> (__tests__/attributes.spec.js:163:17)

  ● Attribute tests › Delete attribute - empty

    Array contains invalid value: 15,NaN

      47 |   const buffer = [];
      48 |   const iv = uuid(null, buffer);
    > 49 |   const aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
         |                  ^
      50 |   const encryptedBytes = aesCbc.encrypt(paddedBytes);
      51 |   const encryptedHex = aesjs.utils.hex.fromBytes([...iv, ...encryptedBytes]);
      52 |   return encryptedHex;

      at coerceArray (node_modules/aes-js/index.js:40:23)
      at new coerceArray (node_modules/aes-js/index.js:195:20)
      at new ModeOfOperationCBC (node_modules/aes-js/index.js:444:21)
      at encrypt (src/lib/utils.js:49:18)
      at Object.<anonymous> (__tests__/attributes.spec.js:178:22)

  ● Attribute tests › Get application shared attributes - age

    Array contains invalid value: 15,NaN

      47 |   const buffer = [];
      48 |   const iv = uuid(null, buffer);
    > 49 |   const aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
         |                  ^
      50 |   const encryptedBytes = aesCbc.encrypt(paddedBytes);
      51 |   const encryptedHex = aesjs.utils.hex.fromBytes([...iv, ...encryptedBytes]);
      52 |   return encryptedHex;

      at coerceArray (node_modules/aes-js/index.js:40:23)
      at new coerceArray (node_modules/aes-js/index.js:195:20)
      at new ModeOfOperationCBC (node_modules/aes-js/index.js:444:21)
      at encrypt (src/lib/utils.js:49:18)
      at Object.<anonymous> (__tests__/attributes.spec.js:198:17)

  ● Attribute tests › Get application shared attributes - age range

    Array contains invalid value: 15,NaN

      47 |   const buffer = [];
      48 |   const iv = uuid(null, buffer);
    > 49 |   const aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
         |                  ^
      50 |   const encryptedBytes = aesCbc.encrypt(paddedBytes);
      51 |   const encryptedHex = aesjs.utils.hex.fromBytes([...iv, ...encryptedBytes]);
      52 |   return encryptedHex;

      at coerceArray (node_modules/aes-js/index.js:40:23)
      at new coerceArray (node_modules/aes-js/index.js:195:20)
      at new ModeOfOperationCBC (node_modules/aes-js/index.js:444:21)
      at encrypt (src/lib/utils.js:49:18)
      at Object.<anonymous> (__tests__/attributes.spec.js:237:17)

PASS __tests__/root.spec.js
FAIL __tests__/applications.spec.js
  ● Application tests › Get shared attributes - sort

    Array contains invalid value: 15,NaN

      47 |   const buffer = [];
      48 |   const iv = uuid(null, buffer);
    > 49 |   const aesCbc = new aesjs.ModeOfOperation.cbc(key, iv);
         |                  ^
      50 |   const encryptedBytes = aesCbc.encrypt(paddedBytes);
      51 |   const encryptedHex = aesjs.utils.hex.fromBytes([...iv, ...encryptedBytes]);
      52 |   return encryptedHex;

      at coerceArray (node_modules/aes-js/index.js:40:23)
      at new coerceArray (node_modules/aes-js/index.js:195:20)
      at new ModeOfOperationCBC (node_modules/aes-js/index.js:444:21)
      at encrypt (src/lib/utils.js:49:18)
      at Object.<anonymous> (__tests__/applications.spec.js:350:22)

PASS __tests__/walkthrough.spec.js

Test Suites: 2 failed, 3 passed, 5 total
Tests:       15 failed, 24 passed, 39 total
Snapshots:   0 total
Time:        2.58s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by smulube** [comment]
I think this has been resolved with some updates to the README. The crucial additions need to be:

1. The hex string used for testing must be the correct length (16, 24 or 32 bytes).
2. If you have once run the test suite with an invalid `.env` file, then you must clear jest's cache after changing it with the following command: `yarn test --clearCache`
